$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        500:{
            item:1,
        },
        768:{
            items:3
        },
        1000:{
            items:4
        }
    }
})