
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        450:{
            items:2
        },
        720:{
            items:3
        },
        1000:{
            items:4
        }
    }
})